### ISSUE TITLE
Сбор новостей

### ISSUE THREAD

**Issue by it-efrem** [Evgeny-Bukovski/NewsBot#1]
- [x] Сформировать базу новостных сайтов

- [x] Проверка XML на валидность

- [x] Решить проблему с кодировками

- [x] Проверить XML парсинг и настроить его. Чтобы собиралась только нужная информация

- [x] Очистка текста от ненужных символов и прочего мусора

**Comment by Evgeny-Bukovski** [comment]
Проверить XML парсинг и настроить его. Чтобы собиралась только нужная информация
