### ISSUE TITLE
Различные замечания

### ISSUE THREAD

**Issue by it-efrem** [Evgeny-Bukovski/NewsBot#5]
- [x] Убрать где не нужно ToLowerCase и использовать "i" в регулярках, Comparator::canonization - почему не работает (?i) ?

- [x] Фиксануть алгоритм нормализации: "Дочери" = "Дочерний", вместо "Дочь"

- [x] Сделать управляющую консоль

- [x] Изменить формат хранимой даты

- [ ] Исправить Comparator.java:173

- [ ] Разобраться с сайтами к которым происходит ошибка подключения

- [ ] Рефакторинг. Переработать объектную модель к лучшему виду

**Comment by Evgeny-Bukovski** [comment]
- [ ] Переработать объектную модель к лучшему виду
